site_name: Datamanagement Workshop at MPI Berlin
site_author: Adina Wagner & Lennart Wittkuhn
repo_url: https://github.com/adswa/mpi-datamanagement-ws
site_url: https://adswa.github.io/mpi-datamanagement-ws/
repo_name: adswa/mpi-datamanagement-ws
docs_dir: docs
copyright: 'Copyright &copy 2020 Adina Wagner & Lennart Wittkuhn'
nav:
  - Data Management Workshop with DataLad: index.md
  - Preperations for participants: content/getting_started.md
  - Content:
      - Welcome: content/welcome.md
      - Motivation: content/motivation.md
      - Basic Principles: content/basicprinciples.md
      - Reproducible Science: content/reproduciblescience.md
      - Data publication: content/datapublication.md
      - Collaboration: content/collaboration.md
  - Behind the scenes:
      - Dashboard: organization/dashboard.md
      - Ideas: organization/ideas.md
      - Goals: organization/goals.md
  - Frequently Asked Questions: FAQ.md
  - Contributing: contributing.md
  - Code of Conduct: coc.md
markdown_extensions:
    - admonition
    - codehilite:
        linenums: true
        guess_lang: false
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
    - toc:
        baselevel: 2
        permalink: true
        separator: "_"
        toc_depth: 3
        anchorlink: false
theme:
    name: material
    language: en
    palette:
        primary: 'black'
        accent: 'yellow'
plugins:
    - search
